export const state = {
  institutions: [],
  selectedInstitutionId: "",
  colleges: [],
  selectedCollegeId: "",
  selectedMajorId: "",
  selectedTrackId: "",
  plan: null,
  resolved: null,
  diagnostics: null,
  pageLayouts: [],
  dirty: false,
  previewTimer: null,
  searchTimer: null,
  settings: null,
  courseColors: {},
  sharedSemesterSets: [],
  sharedSetDraft: null,
  sharedSetResolved: null,
  sharedSemesterPreviewTimer: null,
  sharedElectivePreviewTimer: null,
  sharedSetDirty: false,
  sharedElectiveGroups: [],
  sharedElectiveDraft: null,
  sharedElectiveResolved: null,
  sharedElectiveDirty: false,
};
